### ISSUE TITLE
Manque l'année dans le tableau/formulaire habitat

### ISSUE THREAD

**Issue by lchevall** [oafs72/plateforme_znieff_sav#10]
Il faut afficher les années dans le tableau des habitats pour faciliter le contrôle.

Proposition de Sylvain Bonifait

**Comment by SB-Aq** [comment]
Si problème d'ergonomie, je suppose qu'on peut diminuer un peu la largeur des champs "codes" (aussi larges que les libellés sinon plus sur mon interface).
La mention des années est d'autant plus importante que la déterminance des habitats sera également fonction de l'obsolescence des données (12 ou 24 ans).

**Comment by SB-Aq** [comment]
Idéalement, çà aurait été bien de voir aussi les sources, parce que çà ne permettrait de voir rapidement ce qu'il y a besoin d'actualiser (les sources sont souvent manquantes dans les fiches pré-existantes) - mais je ne sais pas trop si c'est faisable en termes d'ergonomie.

[Idem pour les sources : çà aurait été bien de les voir aussi dans l'interface principale espèces]

**Comment by lchevall** [comment]
Pour les sources et les commentaires :
* Mettre 2 colonnes avec une pastille si l'information est remplie (sans pastille si vide)
* Tooltip (infobulle) en passant sur les pastilles au survol
