### ISSUE TITLE
Import éléments Z1 vers Z2

### ISSUE THREAD

**Issue by SB-Aq** [oafs72/plateforme_znieff_sav#16]
Sur e-znieff, lorsqu'on travaillait sur une Z2, on pouvait importer les espèces et habitats des Z1 filles. Est-ce qu'il serait possible de faire la même chose (pas forcément automatiquement, mais au choix de l'opérateur), du moins si c'est faisable en évitant les doublons ?
Il pourrait également être utile d'importer certains autres éléments (par ex. facteurs d'évolution...) pour pré-remplir la Z2.

**Comment by fauna75** [comment]
- Renseigner les liens entre type II et type I serait facile à développer (et rapide)
- Importer les espèces / habitats et autres informations des types I vers la type II sera beaucoup plus chronophage. Il faudra se réunir pour décider les choix techniques à prendre

**Comment by lchevall** [comment]
Ce développement nécessite des réflexions poussées et des réunions avec le SSI pour définir une manière de fonctionner.
En l'état ce ticket n'est pas réalisable.

**Comment by lchevall** [comment]
- Pouvoir gérer via la fiche ZNIEFF des relations ZNIEFF à ZNIEFF (dont Z1/Z2)
 - Pouvoir importer les espèces et / ou habitats depuis une Z1
   - Importer toutes les espèces puis supprimer celles qu'on ne veut pas ?
   - Choisir les espèces à importer ?
   - Si l'espèce existe déjà dans la fiche, refuser l'import ? Importer quand même en fusionnant les infos (comme pour la fusion de deux espèces sur base de nomenclature) ? Que faire si la fusion n'est pas possible ?
   - Identifier l'origine de l'espèce

**Comment by lchevall** [comment]
**Bilan :** 
 - Plutôt importer toutes les espèces (pas besoin de choisir, le tri se fait après)
 - Ajoute les espèces "à la marge", cad couleur différentes, pas prises en compte dans la vrai liste des espèces (pls si dans pls Z1)
   - Avec bouton "Ajouter l'espèce" si elle n'existe pas déjà
   - Avec bouton "Utiliser les infos de cette espèce" si elle existe déjà (ça remplace les infos)
