### ISSUE TITLE
Contrôle & cohérence zonages Z1/2 [Sujet en marge de la plateforme]

### ISSUE THREAD

**Issue by SB-Aq** [oafs72/plateforme_znieff_sav#18]
Comme la plateforme ne le permet pas, il faudra mettre en cohérence les zonages des ZNIEFF impactées par des ZNIEFF actualisées/créées avant remontée au MNHN. Celà implique un temps de travail dédié (avec Aurélien / Paul ?) sur SIG.
Pour éviter le risque d'avoir des incohérences ou des modifications non anticipées, serait-il possible d'avoir une alerte quelque part (carto, fiche ?) lorsque une modif de zonage entraînes des modifs d'autres zonages ? Cà pourrait être utile pour les rapporteurs et le CSRPN (pour qu'ils puissent se rendre compte d'éventuelles autres modifications) et surtout avant remontée MNHN pour identifier les Z. concernées.

**Comment by lchevall** [comment]
Alerte si :
- intersection de ZNIEFF
- Agrandissement type 1 qui impacte type 2 (ou inversement)

**Comment by lchevall** [comment]
Voir ticket #48
