### ISSUE TITLE
Transfert données flore OBV -> plateforme

### ISSUE THREAD

**Issue by SB-Aq** [oafs72/plateforme_znieff_sav#20]
Les données importées sur la plateforme incluent des données privées sous clause et des données invalides. N'importer que les données publiques (ou assimilées, c'est à dire sans clause de restriction) et "validées" ou en attente de validation (exclure les données sous clause de restriction ou invalidées).

Pour le statut de validation, garder uniquement :
- «  En attente de validation » ;
- « Probable » ;
- « Certain – très probable » ;
- « non réalisable ».

(prévu par Stéphane pour le prochain transfert)

**Comment by lchevall** [comment]
Problème résolu par Stéphane.

Voir mail du 12 décembre 2022
