### ISSUE TITLE
Gestion de la liste "Espèces non déterminantes" [sujet en marge de la plateforme]

### ISSUE THREAD

**Issue by SB-Aq** [oafs72/plateforme_znieff_sav#23]
Cà correspond à la 3ème liste prévue depuis la mise à jour du guide sur les "autres espèces à enjeux". La gestion de cette liste sur la plateforme (et pour contribuer aux ZNIEFF) nous (ER, RG, SB...) pose problème et je ne suis pas sûr de comprendre ce qu'en attend le MNHN ou la façon dont çà va être géré (remontée MNHN ou pas ? qui la définit ?).
Il serait bien qu'on en discute pour voir ce qu'on en fait.

**Comment by RG-Lim** [comment]
Oui d'autant plus que les modifications des infos des taxons (repro, determinance), la synonymie et les suppression des taxons ne sont pas modifiables "en masse". Trop chronophage pour les listes flores (certaines ZNIEFF peuvent avoir jusqu'à 600 espèces). 
Dans l'immédiat (et avant que des améliorations soient proposées) nous (ER, RG, SB) n'avons pas touché à ces espèces ni DZ ni "à autres enjeux". 
Il faut convenir rapidement de ce que l'on fait de ces espèces avant la remontée des fiches au MNHN.

**Comment by lchevall** [comment]
à voir en SSI
