### ISSUE TITLE
Conservation du tri effectué sur les espèces en cas de modification de périmètre

### ISSUE THREAD

**Issue by SB-Aq** [oafs72/plateforme_znieff_sav#24]
Commentaire Eva : si le périmètre est remodelé, toutes les suppressions réapparaissent.

Suggestion SB : il serait bien que la plateforme puisse conserver ce qui a été traité manuellement en cas de modification de zonage (ou qu'on ait une alerte sur les espèces/données en plus ou en moins).

**Comment by SB-Aq** [comment]
Questions complémentaires SB :
- si on coche la case "terminé" et qu'une modif de périmètre impacte cette espèce : comment est-ce que çà se traduit ? Est-ce qu'on peut le savoir pour recontrôler cette espèce ?
- est-ce que le fait de cocher la case "terminé" fige les informations attributaires ? Si on travaille sur un temps long, on peut avoir des modifications du SINP (suppression/invalidation ou ajouts de données) : il ne faudrait donc pas qu'il y ait des modifs sans qu'on puisse le savoir / les tracer. Comment gère-t'on çà ?

**Comment by lchevall** [comment]
La proposition de figer les informations des espèces "Terminé" me semble être une bonne idée, facile à mettre en place.

Pour les suppressions, je propose de stocker les "cd_nom" supprimés et de ne pas les ajoutés dans la fiche lors de la modification du périmètre. Cela ne concernerait bien sûr que les espèces retrouvées dans les données, pas les espèces ajoutées à la main.
Pour les synthèses supprimées ce ne sera pas nécessaire vu que cocher la case "Terminé" bloquerait l'ajout de synthèse automatiquement.

Si on fait ça, je pense qu'il serait bien de pouvoir accéder aux espèces qui ont été ajoutées via les données mais supprimées par la suite, parce qu'elles ne pourront jamais réapparaître dans la fiche automatiquement. Qu'en pensez-vous ?

**Comment by SB-Aq** [comment]
Je ne suis pas sûr de tout comprendre. Qu’est-ce que tu entends par « synthèses » ? Quand tu dis « ajoutées vie les données », çà fait référence à quoi ? (tout est « ajouté via les données »).
SI on peut identifier sur la liste des espèces, celles supprimées et qu’elles restent en base locale (exclues de la remontée au MNHN), alors ok.

**Comment by SB-Aq** [comment]
Réponse Luc :
Ce que j'appelle synthèse, c'est la biologie (repro, etc).
Non, toutes les espèces ne sont pas ajoutées via les données SINP, elles peuvent aussi être ajoutées manuellement.
Et ce que je voulais dire, c'est que les espèces ajoutées à la main puis supprimées ne feraient pas partie de ces espèces dont on bloquera l'ajout en cas de modification de périmètre.

Pour la liste des espèces supprimées, je pensais plus à les mettre à part pour les consulter au besoin pour ne pas les mélanger aux autres.

**Comment by lchevall** [comment]
Si Espèce est "Terminée" -> On ne l'a modifie pas dans le cas d'un modif de périmètre, mais si valeurs calculées != valeurs saisies (date en dehors) => Alerte (pastille)
Si Espèce a été supprimées (sauf si ajoutée à la main) -> Va dans le tableau des espèces supprimées / ignorées. Lors de la modification de périmètre on n'importe pas ces espèces dans la fiche mais si valeurs calculées != valeurs saisies (date en dehors) => Alerte (pastille) dans le tableau des espèces supprimées.
Alerter sur les espèces qui ne sont pas retrouvées dans le nouveau périmètre. => Déjà fait via l'origine

**Comment by lchevall** [comment]
Quand même mettre une case à cocher dans la validation de périmètre pour ne pas recalculer les espèces - FAIT
