### ISSUE TITLE
Nomenclature espèces - Doublons et synonymes

### ISSUE THREAD

**Issue by SB-Aq** [oafs72/plateforme_znieff_sav#26]
ER : pas de possibilité de modifier le nom cité dans l'ancienne fiche ZNIEFF : il faut recréer une ligne et supprimer l’ancienne. Ou alors il faudrait une actualisation automatique des anciens nom vers le taxref actuel.

**Comment by SB-Aq** [comment]
SB : effectivement, çà pose souci, d'autant qu'on se retrouve avec plusieurs lignes pour le même taxon, d'origine différentes (ancienne fiche, SINP...) donc avec sources et attributs différents. Idéalement, il faudrait pouvoir les fusionner pour garder le nom le plus pertinent et agglomérer l'ensemble des sources et années (sinon il faut le faire manuellement et supprimer les doublons un par un / dans le cas de certains doublons subsp. / sp, il faudra de toute façon faire çà manuellement).

Toutefois, je ne suis pas sûr d'être favorable à une automatisation selon taxref, car ce n'est pas toujours adapté (gestion des subsp / sp, niveau de détail). Et il me semble important de pouvoir traiter certains taxons au cdnom plutôt qu'au cdref, notamment pour les taxons non reconnus par le taxref et/ou dans le cas de statuts différenciés (par ex. en Aquitaine, _Salicornia oliveri_ est protégée mais n'est pas reconnue par F-Gallica (donc taxref), si on automatise une gestion au cdref, on perd l'info sur l'écotype et sur le statut règlementaire...

**Comment by RG-Lim** [comment]
Techniquement est-ce faisable que l’outil rassemble tous les taxons synonymes et charge à l'opérateur de "cocher" le nom valide du moins le nom qu'il souhaite faire apparaitre sur la fiche ?

**Comment by lchevall** [comment]
Proposition : 
- Afficher si plusieurs espèces ont le même cd_ref
- Proposer la fusion (automatique si possible, il peut y avoir des conflits de synthèses) des synonymes avec le même cd_ref (fusion des infos) en choisissant le nom qu'on veut garder
- Comment gérer la fusion automatiquement ? Sources : Toutes ; Années / Abondance : Min et max ; Abondance et suivi de l'espèce ?
- Pouvoir changer le nom de l'espèce (parmi les synonymes du cd_ref saisi)
- Qu'est ce qu'il se passe lors de la modif d'un périmètre ? L'ajout d'espèces depuis le SINP se fait via le cd_ref donc si le périmètre est modifié ça peut ajouter des espèces et généré de nouveaux conflits qui seront à traiter.

**Comment by lchevall** [comment]
Fusion automatique (si possible sinon message d'erreur)
Pouvoir identifier si 2 ligne avec même cd_ref (bouton afficher les doublons ou couleur) et proposer fusion

**Comment by lchevall** [comment]
**Bilan :**
Afficher une colonne cd_ref
Pouvoir identifier les doublons
Pouvoir changer le nom de l'espèce parmi les synonymes
La fusion automatique pose trop de problème pour l'isntant
