### ISSUE TITLE
Mise à jour données OBV dans la plateforme

### ISSUE THREAD

**Issue by RG-Lim** [oafs72/plateforme_znieff_sav#30]
Actuellement les données de l'OBV sont reversées dans la plateforme à pas de temps trop distants les uns des autres (2 mois ?). Il faudrait le raccourcir pour pouvoir travailler sur les ZNIEFF directement après la période de terrain, le temps que les saisisseurs aient le temps de saisir. Je propose à minima tous les 15j.

**Comment by SB-Aq** [comment]
Tout à fait, par exemple actuellement, il nous manque les données saisies cet automne. D'accord avec Rémi, il nous faudrait une actualisation tous les 15 jours (voire moins si possible).

**Comment by steph-del** [comment]
J'ai adapté mon script de mise à jour des données. Une mise à jour journalière est prévue prochainement. Nous attendons la fin de quelques travaux sur Lobelia et ce sera disponible pour janvier 2023.

En attendant, je vais faire des mises à jour hebdomadaires.

**Comment by SB-Aq** [comment]
Vu à l'instant avec Stéphane : actuellement il y a à peu près une transmission manuelle par semaine (par SD) ; il est prévu prochainement (mars-avril ? - après MAJ prévue script-Lobelia) de passer à une transmission automatique journalière (à l'avenir, gérée par JRL).

**Comment by steph-del** [comment]
Les tests ont été concluants. La mise à jour des données s'effectue de manière journalière, ce depuis le 12/06/2023.  

Chaque soir à 21h, **les données OBV de la veille sont synchronisées** avant moissonnage et intégration dans la ptf ZNIEFF chaque nuit.

Vous avez donc accès aux données OBV à J-1.
