### ISSUE TITLE
Zonages étranges

### ISSUE THREAD

**Issue by SB-Aq** [oafs72/plateforme_znieff_sav#32]
Je viens de voir sur la plateforme des zonages bizarres (il y en a peut-être d’autres) : 

![image](https://user-images.githubusercontent.com/119489673/205256266-bfc2b544-163a-4b83-a9f4-3f3c6f544c6f.png)
![image](https://user-images.githubusercontent.com/119489673/205256301-5b5ecbb3-36ff-491a-b215-8ba543bc7216.png)
![image](https://user-images.githubusercontent.com/119489673/205256720-44d99be8-7f36-4fd4-9cae-1b717b2c4382.png)

  
Est-ce que ce sont des sites tests pour les formations plateforme ? (si oui, il faudrait les enlever).

Ou si çà correspond à des zonages arbitraires pour des sites sur lesquels il n’y a pas encore de périmètres, est-ce que çà peut être problématique pour les droits d’édition car les zonages ne se trouvent pas forcément sur le bon département.

**Comment by lchevall** [comment]
J'ai supprimé "Coteaux de Ruelle-sur-Touvre", c'était un doublon, sûrement une erreur lors de la création d'une Znieff.

Pour  "Hêtrais de Buros et de Laveyron", c'est effectivement un zonage arbitraire qui peut poser problème pour les droits. Est-ce que tu pourrais me fournir un périmètre approximatif de la localisation pour que les droits soient bons ?

**Comment by SB-Aq** [comment]
Merci - c'est possible qu'il y ait d'autres zonages bizarres ou des sites tests ... on verra au fur à mesure
Pour la Hêtraie de Buros et Laveyron, c'est dans les Landes (en limite avec le Gers ou les Hautes-Pyrénées) - pour les droits, il faut que Josselin et moi puissions bosser dessus.

**Comment by lchevall** [comment]
C'est bon pour "Hêtrais de Buros et de Laveyron".

Et oui on est pas à l'abri d'erreurs de création, il suffit de me le notifier et je corrigerai si ça se reproduit. En attendant je clos ce ticket.

**Comment by ER-CBNSA** [comment]
Pour les Coteaux de Ruelle-sur-Touvre, c'est en effet une erreur. Théo n'arrivant pas a créer la ZNIEFF (finalement problème de géométrie), j'ai fait un test de création de mon côté.
Par contre n'y aurait-il pas la possibilité de supprimer nous-même des "Créations"?
