### ISSUE TITLE
Rubrique Espèces: Période d'observation

### ISSUE THREAD

**Issue by ER-CBNSA** [oafs72/plateforme_znieff_sav#34]
Période d’observation faussée (pour la flore en tout cas ) : « XXXX – 2022 » -  Le « 2022 » est présent même quand l’espèce n’a pas été revue récemment…

**Comment by lchevall** [comment]
Problème corrigé, c'était lié à l'absence de date dans l'import des données nationales.
Maintenant quand il n'y avait pas de données disponibles j'ai mis 1758 -1758.
