### ISSUE TITLE
Nouveau bug: Les données OBV et Fauna ne sont plus prises en compte lors de validation de périmètre!

### ISSUE THREAD

**Issue by ER-CBNSA** [oafs72/plateforme_znieff_sav#36]
Maintenant, lors de la validation d'un périmètre, les données OBV et Fauna ne sont plus prises en compte (uniquement les données issues de la fiche ZNIEFF).

**Comment by lchevall** [comment]
Un arrêt du serveur dans la nuit du 13 décembre a entré un problème sur l'insertion des données faune/flore.
Le problème a été corrigé.

**Comment by ER-CBNSA** [comment]
Parfait merci!
