### ISSUE TITLE
Problèmes de statut de certaines ZNIEFF

### ISSUE THREAD

**Issue by lchevall** [oafs72/plateforme_znieff_sav#4]
Toutes les ZNIEFF actualisées et validées en CSRPN, mais pas encore validées MNHN ont le statut « Actualisation (En cours d'édition) », alors qu’il devrait être « Validé CSRPN »

Problème rencontré par Eva Richez

**Comment by lchevall** [comment]
Remarque de David Naudon également : 

> Dans la tableau de bord des znieff creuse, corrèze, haute-vienne, quand
je sélectionne statut = "en cours d’édition" apparaissent 10 znieff.

> 1/ Sur ces 10 znieff , 4 ont déjà été validées par différents CST
limoges (j'ai tout noté dans les commentaires de chaque Z). Est-ce au
SSI de changer le statut des Z déjà validées par les CST limoges (les 4)
? je les passe en "validée CSRPN" ?

> 2/ Pour les autres le SSI limousin n'est pas à l'origine de ce statut
"en cours d’exécution" :
     - J'imagine que pour les Z à cheval avec les départements voisins
ce sont les SSI voisins qui sont à l'origine de ce statut ?
     - Pour "pelouse calcaire de st robert" je ne vois pas d'où ce
statut peut venir.

**Comment by lchevall** [comment]
Les problèmes de statuts relevés par David ont été corrigés.
Ceux du Poitou-Charente sont en cours

**Comment by SB-Aq** [comment]
Idem Eva : pour l'Aquitaine, la plateforme liste 153 Z. avec le statut "Actualisation (En cours d'édition)" - ce qui ne correspond pas à notre avancement (et d'ailleurs certaines Z. indiquées en cours d'édition ne sont pas éditables).
Je n'ai pas regardé le détail du reste, mais j'ai l'impression qu'il y a aussi d'autres statuts erronés.

**Comment by lchevall** [comment]
Pour l'aquitaine : il y avait un mauvais statut pour "Forêt usagère de la Teste de Buch", c'est corrigé.

Pour les autres, ce sont les ZNIEFF qui étaient dans le fichier de suivi rubrique "Znieff en reserve". Je les ai mis en "En cours d'édition".
Est-ce que j'aurai du laisser ces ZNIEFF en "Validé MNHN" ?

**Comment by SB-Aq** [comment]
Je pense, oui : ce ne sont pas des ZNIEFF sur lesquelles on travaille actuellement mais la liste qui alimentera la programmation des prochaines années.

**Comment by lchevall** [comment]
Les ZNIEFF en reserve pour l'Aquitaine ont été repassées en Valide MNHN.

**Comment by lchevall** [comment]
Les problèmes soulevés par Eva dans le PC ont été corrigés.
Vérifications encore nécessaires dans toute la NA pour s'assurer que tout colle.
