### ISSUE TITLE
export de la dernière version d'un périmètre à partir de l'espace de travail

### ISSUE THREAD

**Issue by RG-Lim** [oafs72/plateforme_znieff_sav#47]
Peut-être que ça existe déjà, mais serait-il possible de permettre l'export d'un périmètre sans repasser par le module "remodifier le périmètre" pour éviter de remettre à zéro la liste des espèces DZ. En effet, on peut être amené à avoir créer/modifier le périmètre de la ZNIEFF directement sur la plateforme sans pour autant avoir pensé à exporter la dernière version. Nous n'avons donc pas la table SIG de cette dernière version autrement qu'en allant dans remodifier le périmètre et donc de bouger la liste des espèces...

Evolution souhaitable mais non bloquante.

Merci.

**Comment by lchevall** [comment]
![image](https://github.com/fauna75/plateforme_znieff_sav/assets/57537541/385133f4-78bb-481d-b30a-b2b57fdd6165)

Tu peux télécharger le périmètre depuis la fiche en cours dans l'onglet "Identification du site" via le petit bouton sous les bouton de zoom dans la carte.
