### ISSUE TITLE
Ajout de champs dans la fiche ZNIEFF

### ISSUE THREAD

**Issue by lchevall** [oafs72/plateforme_znieff_sav#7]
Rubrique Identification :
- Champ texte "Rédacteurs"
- *Pas nécessaire* Champ entier "Année de rédaction"
- Champ entier "Altitude" -> Sera renseigné automatiquement lors de l'export au MNHN
- Champ autocompletion multiple "Relation ZNIEFF à ZNIEFF" (x2  : Relation parent/enfant / Liens écologiques)

Ajouts proposés par Sylvain Bonifait

**Comment by SB-Aq** [comment]
Le champ rédacteur devrait importer ce qui est dans la fiche pré-existante, mais être éditable pour être complété par les opérateurs ; il n'y a pas besoin d'un champs distinct "année de rédaction", puisque l'année est saisie dans le même champ (cf. vademecum), par exemple : "CBNSA (Bonifait S.), 2020 ; FAUNA (Lapié P.), 2022 ; [GEREA]".

Pour les liaisons écologiques avec d'autres ZNIEFF, çà peut-être renseigné automatiquement dans le cas de liaisons mère-fille, mais dans le cas de sites adjacents/proches, il faudrait que ce soit rempli par l'opérateur.

**Comment by lchevall** [comment]
On ajoute juste le champ "rédacteur" en texte libre

**Comment by lchevall** [comment]
Concernant les altitudes (min et max) :

- ajout des champs dans le formulaire (mais pas en mode édition)
- calculés lors de l'export, renseignée dans la fiche à ce moment là.

La superficie est calculée au moment de la validation finale d'un périmètre => ajout dans la fiche de consultation, mais pas en édition

**Comment by lchevall** [comment]
Résumé : 
* rédacteur : obligatoire - OK
* superficie : souhaitable
* altitude : à voir plus tard lors de la remontée
* relations Z² (2 champs) : souhaitable, obligatoire si pas long
