### ISSUE TITLE
Facteurs d'évolution, inversion des rubriques et des légendes

### ISSUE THREAD

**Issue by lchevall** [oafs72/plateforme_znieff_sav#9]
Dans le tableau des facteurs d'évolution, les titres de colonne et les valeurs sont inversées.
À corriger.

Problème rencontré par Sylvain Bonifait

**Comment by lchevall** [comment]
Selon la structure de la Base de données ZNIEFF (PDF et export CSV), les rubriques sont dans le bon ordre.
Il semblerait donc que ce soit sur la plateforme nationale que les rubriques sont inversées.

**Comment by SB-Aq** [comment]
Il faut vérifier au préalable auprès du MNHN ce qui est correct, car si c'est bon sur la plateforme, çà veut dire que c'est inversé sur e-znieff et l'INPN et donc ce qu'on notera sur la plateforme sera erroné à la diffusion... ce qui sera également problématique...

**Comment by lchevall** [comment]
Luc contacte Matthieu MANCEAU + Fanny LEPAREUR (appeler)

**Comment by lchevall** [comment]
La doc était correct, les rubriques sont dans le bon ordre.
C'est dans la plateforme nationale que c'est inversé.
